---
title: "plots"
author: "Maisy Hallam"
date: "2024-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(ggtext)
```

# Plots

Set theme.

```{r}
theme_set(theme_minimal(base_size = 25))
theme_update(axis.line.x = element_line(color = "black"),
    axis.line.y = element_line(color = 'black'))
```

## Comparing real distribution with simulated distribution.

```{r}
# sims <- read_csv('../data/raw/simulated-mi.csv')
# sims <- filter(sims, mutual_information > 0)
# kb <- read_csv('../data/raw/kinbank-mi.csv')

sims <- read_csv('../data/raw/simulated_mi_FINAL.csv')
# sims <- filter(sims, mutual_information > 0)
kb <- read_csv('../data/raw/kinbank_mi_FINAL.csv')

sims <- sims %>% filter(true_value > 0)
kb <- kb %>% filter(mutual_information > 0)

# 
# sims <- filter(sims,mutual_information > 0)
```

```{r}
facet_labels <- c(
                    'Y' = 'random baseline',
                    'N' = 'natural languages'
                    )

rbind(select(sims, -c(true_value)),kb) %>%
  ggplot(aes(mutual_information, fill = simulation, colour = simulation)) +
  scale_fill_manual(values = c('#d95f50','#7570b3'),
                    name="data type:",
                    labels=c("natural languages", "random baseline")) +
  scale_colour_manual(values = c('#d95f50','#7570b3'),
                      name="data type:",
                    labels=c("natural languages", "random baseline")) +
  geom_histogram(alpha=0.5) +
  # ggtitle('Distribution of mutual information for real and simulated kinship systems') +
  xlab('Mutual information (bits)') +
  theme(
    legend.position = 'none') +
  facet_wrap(~simulation, scales = 'free', nrow = 2,labeller = as_labeller(facet_labels))

ggsave('../plots/sims_kb_distributions_HIST.png')
```

```{r}
sims %>%
  ggplot(aes(mutual_information, fill = simulation, colour = simulation)) +
  scale_fill_manual(values = c('#7570b3'),
                    name="data type:",
                    labels=c("random baseline")) +
  scale_colour_manual(values = c('#7570b3'),
                      name="data type:",
                    labels=c("random baseline")) +
  geom_density(alpha = 0.8) +
  # ggtitle('Distribution of mutual information for real and simulated kinship systems') +
  xlab('Mutual information (bits)') +
  theme(
    legend.position = c(0.7, 0.8))


ggsave('../plots/sims_ONLY_distributions.png')
```


## Comparing simulated distribution with real value for individual languages

```{r}
sample <- read_csv('../data/processed/sampled_data_UPDATED.csv')
```

```{r}
ie <- filter(sample,language_family == 'Indo-European') %>%
  ggplot(aes(simulated_value)) +
  geom_histogram(colour = '#d95f02', fill = '#d95f02') +
  geom_vline(aes(xintercept = real_value),linetype = 4) +
  ggtitle('Indo-European') +
  xlab('') +
  facet_grid(~language)

ie
```

```{r}
au <- filter(sample,language_family == 'Austronesian') %>%
  ggplot(aes(simulated_value)) +
  geom_histogram(colour = '#7570b3', fill = '#7570b3') +
  geom_vline(aes(xintercept = real_value),linetype = 4) +
  ggtitle('Austronesian') +
  xlab('') +
  facet_grid(~language)

au
```

```{r}
pn <- filter(sample,language_family == 'Pama-Nyungan') %>%
  ggplot(aes(simulated_value)) +
  geom_histogram(colour = '#1b9e77', fill = '#1b9e77') +
  geom_vline(aes(xintercept = real_value),linetype = 4) +
  ggtitle('Pama-Nyungan') +
  xlab('') +
  facet_grid(~language)

pn
```

```{r}
ie + au + pn +
  plot_layout(nrow = 3)
```
Small sample of languages for evolang abstract.

```{r}
sample2 <- read_csv('../data/processed/sample_for_evolang.csv')

sample2
```

```{r}
sample2 %>%
  ggplot(aes(x = simulated_value, fill = language,colour = language)) +
  scale_fill_manual(values = c('#d95f50','#7570b3','#1b9e77','#ffeda0')) +
  scale_colour_manual(values = c('#d95f50','#7570b3','#1b9e77','#ffeda0')) +
  geom_density() +
  geom_vline(aes(xintercept = real_value),linetype = 'dashed') +
  geom_richtext(data=z_labels, mapping=aes(x= 1.6, y=8, label=paste0('<i>z = </i>', round(z,2))), inherit.aes = FALSE) +
  facet_wrap(~language) +
  labs(x = 'Mutual information (bits)',
       y = 'density') +
  theme_bw(base_size = 18) +
  theme(legend.position = 'none')

ggsave('../plots/small_sample_grid.png',width = 5,height = 5)
```


## Plot participant z-scores relative to 1.96 SD.

```{r}
lang_z <- read_csv('../data/processed/z_scores_UPDATED.csv')
```


```{r}
lang_z %>% filter(zscore != 0) %>%
  ggplot(aes(x = language_family, y = zscore)) +
  geom_point(aes(colour = language_family),alpha = 0.3) +
  geom_hline(yintercept = 1.96, linetype = 'dashed') +
  geom_hline(yintercept = -1.96, linetype = 'dashed') +
  xlab('Language family') +
  theme_bw() +
  theme(legend.position = 'none') +
  # theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  coord_flip()



```

